### ISSUE TITLE
Screenshot isn't  loading

### ISSUE THREAD

**Issue by moultz** [aaronksaunders/parse-starter-ionic#3]
http://cl.ly/image/0z2z1x1E1D0B/Image%202015-03-22%20at%209.49.55%20PM.png doesn't appear to work in Readme

**Comment by aaronksaunders** [comment]
Thanks, i will take a look and update

On Thursday, July 16, 2015, moultz notifications@github.com wrote:

> http://cl.ly/image/0z2z1x1E1D0B/Image%202015-03-22%20at%209.49.55%20PM.png
> doesn't appear to work in Readme
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aaronksaunders/parse-starter-ionic/issues/3.

## 

## -- http://www.clearlyinnovative.com/build-it/

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by aaronksaunders** [comment]
fixed @moultz
