### ISSUE TITLE
Displays same info in account tab when logging out and creating a new account

### ISSUE THREAD

**Issue by SourceCodeplz** [aaronksaunders/parse-starter-ionic#5]
Firstly thanks a lot for this starter Aaron, its really helpful, hope we can make it even better.

The issue relates to when the user creates an account, logs out and then creates a new account.
The info in the /tab/account is the one from the first account, which the user is now logged out of.

**Comment by aaronksaunders** [comment]
Will look into this over the next few days

Aaron K. Saunders
CEO Clearly Innovative Inc. 
aaron@clearlyinnovative.com 
201.214.5926  (M) 
blog@clearlyinnovative.com
www.clearlyinnovative.com 
@aaronksaunders

An Appcelerator Titanium Gold Partner

This email message and any attachment(s) are for the sole use of the intended recipient(s) and may contain proprietary and/or confidential information which may be privileged or otherwise protected from disclosure. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient(s), please contact the sender by reply email and destroy the original message and any copies of the message as well as any attachment(s) to the original message.
